# プロジェクト名
name: Training
# バンドルID
options:
  # バンドルプレフィックス
  bundleIdPrefix: algoria.Training
  # LocalizationsのDevelopment Languageを指定
  developmentLanguage: ja
  
  
# ターゲットごとの設定
targets:
  Training:
    # ターゲットの製品タイプ
    type: application
    # ターゲットのプラットフォーム
    platform: iOS
    # デプロイメントターゲット
    deploymentTarget: "16.0"
          
    sources:
      - Training
      
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: algoria.Training
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: algoria
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -all_load

    info:
      path: Training/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
          
  TrainingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TrainingTests
    settings:
      base:
        INFO_PLIST_FILE: TrainingTests/Info.plist
    dependences:
      - target: Training
        
  TrainingUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: TrainingUITests
    settings:
      base:
        INFOPLIST_FILE: TrainingUITests/Info.plist
    dependencies:
      - target: Training


